 const data = [
    {
      id: 1,
      name: "Buttermilk Pancakes",
      category: "Breakfast",
      price: 15.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-1.jpeg",
      desc: "I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed.",
    },
    {
      id: 2,
      name: "Diner Double",
      category: "Lunch",
      price: 13.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-2.jpeg",
      desc: "Vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats.",
    },
    {
      id: 3,
      name: "Godzilla Milkshake",
      category: "Shakes",
      price: 6.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-3.jpeg",
      desc: "Kombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.",
    },
    {
      id: 4,
      name: "Country Delight",
      category: "Breakfast",
      price: 20.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-4.jpeg",
      desc: "Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut.",
    },
    {
      id: 5,
      name: "Egg Attack",
      category: "Lunch",
      price: 22.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-5.jpeg",
      desc: "Franzen vegan pabst bicycle rights kickstarter meditation farm-to-table 90's pop-up.",
    },
    {
      id: 6,
      name: "Oreo Dream",
      category: "Shakes",
      price: 18.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-6.jpeg",
      desc: "Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday.",
    },
    {
      id: 7,
      name: "Bacon Overflow",
      category: "Breakfast",
      price: 8.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-7.jpeg",
      desc: "Carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird on it.",
    },
    {
      id: 8,
      name: "American Classic",
      category: "Lunch",
      price: 12.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-8.jpeg",
      desc: "On it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut.",
    },
    {
      id: 9,
      name: "Quarantine Buddy",
      category: "Shakes",
      price: 16.99,
      img: "https://react-projects-5-menu.netlify.app/images/item-9.jpeg",
      desc: "Skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.",
    },
    {
      id: 10,
      name: "Avocado Toast Supreme",
      category: "Breakfast",
      price: 11.49,
      img: "https://images.unsplash.com/photo-1553163147-622ab57e0cc0",
      desc: "Activated charcoal toast topped with avocado smash, poached egg, and microgreens for a healthy start.",
    },
    {
      id: 11,
      name: "Classic BLT Sandwich",
      category: "Lunch",
      price: 14.25,
      img: "https://images.unsplash.com/photo-1606755962773-0e6b2dbb52a6",
      desc: "Smoked bacon, fresh lettuce, and juicy tomatoes served on toasted sourdough bread.",
    },
    {
      id: 12,
      name: "Berry Blast Smoothie",
      category: "Shakes",
      price: 7.49,
      img: "https://images.unsplash.com/photo-1570197571499-166b36435e9e",
      desc: "A mix of strawberries, blueberries, and raspberries blended with almond milk and honey.",
    },
    {
      id: 13,
      name: "Veggie Delight Omelette",
      category: "Breakfast",
      price: 10.99,
      img: "https://images.unsplash.com/photo-1551218808-94e220e084d2",
      desc: "Loaded with spinach, mushrooms, peppers, and cheese — fluffy and flavorful.",
    },
    {
      id: 14,
      name: "Spicy Chicken Wrap",
      category: "Lunch",
      price: 13.49,
      img: "https://images.unsplash.com/photo-1590080875831-fc1e28b31e4b",
      desc: "Grilled chicken, spicy sauce, lettuce, and tomato wrapped in a soft tortilla.",
    },
    {
      id: 15,
      name: "Chocolate Heaven Shake",
      category: "Shakes",
      price: 9.99,
      img: "https://images.unsplash.com/photo-1612197527779-9d4d5c8f70b3",
      desc: "Rich chocolate ice cream with whipped cream and fudge topping for a decadent treat.",
    },
    {
      id: 16,
      name: "French Toast Delight",
      category: "Breakfast",
      price: 12.49,
      img: "https://images.unsplash.com/photo-1565958011705-44e2119b5b32",
      desc: "Golden-brown French toast topped with maple syrup and fresh berries.",
    },
    {
      id: 17,
      name: "Grilled Cheese & Soup Combo",
      category: "Lunch",
      price: 15.25,
      img: "https://images.unsplash.com/photo-1625940965760-df58b3c21b0f",
      desc: "Classic grilled cheese sandwich served with hot tomato basil soup.",
    },
    {
      id: 18,
      name: "Peanut Butter Banana Shake",
      category: "Shakes",
      price: 8.75,
      img: "https://images.unsplash.com/photo-1577805947697-89e18249d767",
      desc: "Creamy peanut butter and banana blended into a thick, smooth milkshake.",
    },
    {
      id: 19,
      name: "Sunny Side Breakfast Bowl",
      category: "Breakfast",
      price: 14.99,
      img: "https://images.unsplash.com/photo-1525351484163-7529414344d8",
      desc: "Scrambled eggs, avocado, roasted veggies, and quinoa topped with herbs.",
    },
    {
      id: 20,
      name: "Mediterranean Salad",
      category: "Lunch",
      price: 17.49,
      img: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
      desc: "A fresh blend of lettuce, olives, feta cheese, and cherry tomatoes with olive oil dressing.",
    },
  ];
export default data;
